# Generated by Django 4.2.6 on 2024-01-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
    ]
